/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.Administrador;

import controller.AdministradorCtrl;
import dao.AdministradorImp;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import model.entidades.Persona;
import model.entidades.Usuario;

/**
 *
 * @author HAYDEE
 */
public class RegistrarAdministrador extends javax.swing.JFrame {

    private String rol;
    private int idAdministrador;
    private final AdministradorCtrl adminCtrl;

    public RegistrarAdministrador(String rol, int idAdministrador) {
        this.rol = rol;
        this.idAdministrador=idAdministrador;
        this.adminCtrl= new AdministradorCtrl(
        AdministradorImp.obtenerInstancia()
        );
        initComponents();
        jlblrol.setText(rol);
        jcmbrol.setSelectedItem(rol);
        jcmbrol.setEnabled(false);

    }
    
    public void registrar(){
        String nombre=jtxtnombre.getText();
        String apellido=jtxtapellido.getText();
        String dni=jtxtdni.getText();
        Date fechaNacimiento=jDatenacimientoAlumno.getDate();
        String telefono=jtxttelefono.getText();
        String correo=jtxtcorreo.getText();
        String direccion=jtxtdireccion.getText();
        String genero= (String) jcmbgenero.getSelectedItem();
        String username=jtxtnombreusuario.getText();
        String contraseña=jPasswordFieldcontraseña.getText();
        String estado=(String) jcmbestado.getSelectedItem();
        
        LocalDate FechaActual = LocalDate.now();
        LocalDate fechaNacimientoLocal = fechaNacimiento.toInstant()
                                    .atZone(ZoneId.systemDefault())
                                    .toLocalDate();
        
        if(nombre.isBlank() || apellido.isBlank() || fechaNacimientoLocal.isAfter(FechaActual) || fechaNacimiento==null || correo.isBlank() || direccion.isBlank()){
            JOptionPane.showMessageDialog(null, "Debe ingresar todos los datos requeridos");
            
        }else{
            if(!dni.matches("\\d{8}")){
                JOptionPane.showMessageDialog(null, "Dni Invalido");
            }else{
                if(!telefono.matches("\\d{9}")){
                    JOptionPane.showMessageDialog(null, "Numero ingresado invalido");
                }else{
                    if(adminCtrl.verificarDni(dni)==false){
                        JOptionPane.showMessageDialog(null, "Numero de DNI ya se encuentra registrado");
                    }else{
                        Persona persona = new Persona(
                                0,
                                nombre,
                                apellido, 
                                dni, 
                                telefono, 
                                correo, 
                                direccion, 
                                (java.sql.Date) fechaNacimiento,
                                genero);
                        Usuario usuario = new Usuario(
                                0,
                                username,
                                contraseña,
                                rol,
                                estado,
                                persona
                        );
                        adminCtrl.registrar(usuario);
                    }
                }
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlblrol = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcmbrol = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jtxtnombre = new javax.swing.JTextField();
        jtxtapellido = new javax.swing.JTextField();
        jtxtdni = new javax.swing.JTextField();
        jDatenacimientoAlumno = new com.toedter.calendar.JDateChooser();
        jtxttelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtcorreo = new javax.swing.JTextField();
        jtxtdireccion = new javax.swing.JTextField();
        jbtnregistrar = new javax.swing.JButton();
        jbtncancelar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jcmbgenero = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jtxtnombreusuario = new javax.swing.JTextField();
        jPasswordFieldcontraseña = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jcmbestado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Registrar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jlblrol.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlblrol.setText("jLabel2");
        jPanel1.add(jlblrol, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel2.setText("Rol:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel4.setText("Apellido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel5.setText("Fecha de Nacimiento:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel6.setText("DNI:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jcmbrol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jcmbrol, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 140, -1));

        jLabel7.setText("Telefono:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));
        jPanel1.add(jtxtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 170, -1));
        jPanel1.add(jtxtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 170, -1));
        jPanel1.add(jtxtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 170, -1));

        jDatenacimientoAlumno.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jDatenacimientoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 140, -1));

        jtxttelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxttelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(jtxttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 140, -1));

        jLabel8.setText("Correo:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        jLabel9.setText("Direccion:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));
        jPanel1.add(jtxtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 140, -1));
        jPanel1.add(jtxtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 140, -1));

        jbtnregistrar.setText("Registrar");
        jbtnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnregistrarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, -1, -1));

        jbtncancelar.setText("Cancelar");
        jPanel1.add(jbtncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 80, -1));

        jLabel10.setText("Genero:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        jcmbgenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "masculino", "femenino" }));
        jPanel1.add(jcmbgenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 140, -1));

        jLabel11.setText("Nombre de usuario:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));
        jPanel1.add(jtxtnombreusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 140, -1));
        jPanel1.add(jPasswordFieldcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 140, -1));

        jLabel12.setText("contraseña:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 70, -1));

        jLabel13.setText("Estado");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, -1, -1));

        jcmbestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "activo", "inactivo" }));
        jPanel1.add(jcmbestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxttelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxttelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxttelefonoActionPerformed

    private void jbtnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnregistrarActionPerformed
        
    }//GEN-LAST:event_jbtnregistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDatenacimientoAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldcontraseña;
    private javax.swing.JButton jbtncancelar;
    private javax.swing.JButton jbtnregistrar;
    private javax.swing.JComboBox<String> jcmbestado;
    private javax.swing.JComboBox<String> jcmbgenero;
    private javax.swing.JComboBox<String> jcmbrol;
    private javax.swing.JLabel jlblrol;
    private javax.swing.JTextField jtxtapellido;
    private javax.swing.JTextField jtxtcorreo;
    private javax.swing.JTextField jtxtdireccion;
    private javax.swing.JTextField jtxtdni;
    private javax.swing.JTextField jtxtnombre;
    private javax.swing.JTextField jtxtnombreusuario;
    private javax.swing.JTextField jtxttelefono;
    // End of variables declaration//GEN-END:variables
}
